"""add index on products.name

Revision ID: fd09a20752de
Revises: fb870b094e98
Create Date: 2025-09-30 21:22:15.453461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd09a20752de'
down_revision: Union[str, Sequence[str], None] = 'fb870b094e98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_product_name', 'products', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_name', table_name='products')
    # ### end Alembic commands ###
